name: test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - uses: .
        with:
          ssm-path: /opensource/action-aws-ssm-to-dotenv
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
      - run: cat .env

  arguments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - uses: .
        with:
          ssm-path: /opensource/action-aws-ssm-to-dotenv
          prefix: SSM_
          format: shell
          output: .env.test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
      - run: cat .env.test
